name: 🍪 Bake Docker Image

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  bake:
    name: 🍪 Bake Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build${{ startsWith(github.ref, 'refs/tags') && ' and Push to GHCR' || '' }}
        env:
          REGISTRY: ghcr.io/theory
          PUSH: ${{ startsWith(github.ref, 'refs/tags') }}
        run: make image
