name: ✅ Run Test Suite

on:
  push:

jobs:
  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: apt-get install
        run: sudo make apt-install-deps
      - run: make test
