name: ✅ Run Test Suite

on:
  push:

jobs:
  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: apt-get install
        run: >
          sudo apt-get install -y --no-install-recommends
          ca-certificates
          libcryptx-perl
          libio-socket-ssl-perl
          libipc-system-simple-perl
          libterm-termkey-perl
          liburi-perl
          libwww-curl-simple-perl
          postgresql-client
      - run: make test
