name: ✅ Run Test Suite

on:
  push:

jobs:
  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: apt-get install
        run: sudo make deb-install-deps
      - run: make test
      - run: make coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
